### ISSUE TITLE
报错: module 'node_helpers' has no attribute 'pillow'

### ISSUE THREAD

**Issue by Kevin-coder80** [zmwv823/ComfyUI-AnyText#13]
<img width="1044" alt="image" src="https://github.com/zmwv823/ComfyUI-AnyText/assets/2867973/0ace1643-5d02-4bcf-ac60-705a0a556d98">

**Comment by mcx-mcx** [comment]
你这个是因为comfyui版本太低，你可以自己在nodehelper里添加pillow函数

**Comment by Kevin-coder80** [comment]
@mcx-mcx 嗯，升级后就没有这个问题了。
